version: "2"
services:
  ldap:
    image: welharrak/ldapserver19:latest
    container_name: ldapserver
    hostname: ldapserver
    ports: 
      - "389:389"
    networks:
      - ldapnet
  ssh:
    image: welharrak/ssh19:base
    container_name: ssh
    hostname: ssh
    volumes:
      - "homes:/tmp/home"
    ports:
      - "2022:22"
    privileged: true
    networks:
      - ldapnet
networks:
    ldapnet:
volumes:
    homes:
